version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  grpc-server:
    build: ./backend/grpc_server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://library_user:library_pass@db:5432/library_db
      GRPC_PORT: 50051
    ports:
      - "50051:50051"

  node-gateway:
    build: ./backend/node_gateway
    depends_on:
      - grpc-server
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    depends_on:
      - node-gateway
    ports:
      - "3000:80"
